from django.urls import path

from .views import (
    chat_view,
    conversation_detail_view,
    conversations_view,
    current_user,
    document_detail_view,
    documents_view,
    login_user,
    logout_user,
    confirm_password_reset,
    request_password_reset,
    register_user,
    database_connection_view,
    test_database_connection_view,
    database_schema_view,
    execute_sql_query_view,
    sql_query_suggestions_view,
    upload_database_view,
    health_view,
    models_view,
    set_model_view,
    message_feedback_view,
    delete_message_feedback_view,
    user_preferences_view,
    update_user_preferences_view,
    update_user_profile_view,
    change_password_view,
)

app_name = "agent"

urlpatterns = [
    path("health/", health_view, name="health"),
    path("chat/", chat_view, name="chat"),
    path("conversations/", conversations_view, name="conversation-list"),
    path("conversations/<int:conversation_id>/", conversation_detail_view, name="conversation-detail"),
    path("documents/", documents_view, name="document-list"),
    path("documents/<int:document_id>/", document_detail_view, name="document-detail"),
    path("auth/register/", register_user, name="register"),
    path("auth/login/", login_user, name="login"),
    path("auth/logout/", logout_user, name="logout"),
    path("auth/me/", current_user, name="current-user"),
    path("auth/password/reset/", request_password_reset, name="password-reset-request"),
    path("auth/password/reset/confirm/", confirm_password_reset, name="password-reset-confirm"),
    path("auth/password/change/", change_password_view, name="password-change"),
    path("auth/profile/", update_user_profile_view, name="profile-update"),
    path("database/connection/", database_connection_view, name="database-connection"),
    path("database/connection/test/", test_database_connection_view, name="database-connection-test"),
    path("database/upload/", upload_database_view, name="database-upload"),
    path("database/query/", execute_sql_query_view, name="database-query"),
    path("database/query/suggestions/", sql_query_suggestions_view, name="database-query-suggestions"),
    path("database/schema/", database_schema_view, name="database-schema"),
    path("models/", models_view, name="models-list"),
    path("models/set/", set_model_view, name="models-set"),
    path("messages/<int:message_id>/feedback/", message_feedback_view, name="message-feedback"),
    path("messages/<int:message_id>/feedback/delete/", delete_message_feedback_view, name="message-feedback-delete"),
    path("preferences/", user_preferences_view, name="preferences"),
    path("preferences/update/", update_user_preferences_view, name="preferences-update"),
]
